FROM gugod/perlcritic:latest
RUN curl -LO https://github.com/haya14busa/reviewdog/releases/download/0.9.11/reviewdog_linux_amd64 \
    && mv reviewdog_linux_amd64 /usr/local/bin/reviewdog \
    && chmod +x /usr/local/bin/reviewdog
